# Generated by Django 6.0.2 on 2026-05-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_endorsement_fundingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('ORACLE', 'Oracle')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracle_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
