# Generated by Django 6.0.2 on 2026-05-21 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oraclemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('PHYSICAL', 'Physical Card'), ('VIRTUAL', 'Virtual Card')], max_length=20)),
                ('name_on_card', models.CharField(max_length=100)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvc_dummy', models.CharField(default='***', max_length=3)),
                ('is_frozen', models.BooleanField(default=False)),
                ('online_payments', models.BooleanField(default=True)),
                ('international_spend', models.BooleanField(default=False)),
                ('contactless', models.BooleanField(default=True)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('current_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
